# **PCN Model**

In [0]:
# Code from Chapter 2 of Machine Learning: An Algorithmic Perspective
# by Stephen Marsland (http://seat.massey.ac.nz/personal/s.r.marsland/MLBook.html)

# You are free to use, change, or redistribute the code in any way you wish for
# non-commercial purposes, but please maintain the name of the original author.
# This code comes with no warranty of any kind.

# Stephen Marsland, 2008

from numpy import *

def linear_activation(inputs):
  """Linear activation function.
    
    inputs: np.array
  """
  return inputs
  

class pcn:
  """ A basic Perceptron (the same pcn.py except with the weights printed
  and it does not reorder the inputs)"""
	
  def __init__(self,inputs,targets,activation_function=linear_activation):
    """ Constructor """
    # Set up network size
    if ndim(inputs)>1:
      self.nIn = shape(inputs)[1]
    else: 
      self.nIn = 1
	
    if ndim(targets)>1:
      self.nOut = shape(targets)[1]
    else:
      self.nOut = 1

    self.nData = shape(inputs)[0]
	
    # Initialise network
    self.weights = random.rand(self.nIn+1,self.nOut)*0.1-0.05
    # Declare activation function that is to be used prior to quantization
    self.activation = activation_function
    
    self.threshold = 0.5
    

  def pcntrain(self,inputs,targets,eta,nIterations):
    """ Train the thing """	
    # Add the inputs that match the bias node
    inputs = concatenate((inputs,-ones((self.nData,1))),axis=1)

    # Training
    change = range(self.nData)

    for n in range(nIterations):	
      self.outputs = self.pcnfwd(inputs);
      self.weights += eta*dot(transpose(inputs),targets-self.outputs)
      print ("Iteration: ", n)
      print (self.weights)

      activations = self.pcnfwd(inputs)
      print ("Final outputs are:")
      print (activations)
      print ("Thresholded final outputs are:")
      print (where(activations>self.threshold,1,0))

  def pcnfwd(self,inputs):
    """ Run the network forward """

    outputs =  dot(inputs,self.weights)

    # Activate the outputs
    return self.activation(outputs)

  
  def confmat(self,inputs,targets):
    """Confusion matrix"""

    # Add the inputs that match the bias node
    inputs = concatenate((inputs,-ones((self.nData,1))),axis=1)
    outputs = dot(inputs,self.weights)

    nClasses = shape(targets)[1]

    if nClasses==1:
      nClasses = 2
      outputs = where(outputs>self.threshold,1,0)
    else:
      # 1-of-N encoding
      outputs = argmax(outputs,1)
      targets = argmax(targets,1)

    cm = zeros((nClasses,nClasses))
    for i in range(nClasses):
      for j in range(nClasses):
        cm[i,j] = sum(where(outputs==i,1,0)*where(targets==j,1,0))

    print (cm)
    print (trace(cm)/sum(cm))

# **Generate Data**
Use numpy to create the input and target data for pcn model

In [0]:
import numpy as np
inputs = np.array([[0,0],[0,1],[1,0],[1,1]])
targets = np.array([[0],[1],[1],[1]])

# **Train the model**
Create a new `pcn` object and use the function `pcntrain` to train the model. 

In [3]:
p = pcn(inputs, targets)
p.pcntrain(inputs, targets, 0.1, 6)

Iteration:  0
[[ 0.16653308]
 [ 0.17611479]
 [-0.3163422 ]]
Final outputs are:
[[0.3163422 ]
 [0.49245699]
 [0.48287529]
 [0.65899007]]
Thresholded final outputs are:
[[0]
 [0]
 [0]
 [1]]
Iteration:  1
[[ 0.25234655]
 [ 0.26097008]
 [-0.42127575]]
Final outputs are:
[[0.42127575]
 [0.68224583]
 [0.6736223 ]
 [0.93459237]]
Thresholded final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  2
[[ 0.29152508]
 [ 0.29928626]
 [-0.45010212]]
Final outputs are:
[[0.45010212]
 [0.74938838]
 [0.7416272 ]
 [1.04091346]]
Thresholded final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  3
[[ 0.31327101]
 [ 0.32025607]
 [-0.45189901]]
Final outputs are:
[[0.45189901]
 [0.77215508]
 [0.76517002]
 [1.08542609]]
Thresholded final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  4
[[ 0.3282114 ]
 [ 0.33449796]
 [-0.44443399]]
Final outputs are:
[[0.44443399]
 [0.77893194]
 [0.77264539]
 [1.10714334]]
Thresholded final outputs are:
[[0]
 [1]
 [1]
 [1]]
Iteration:  5
[[ 0.34023253]
 [ 0.34589043]
 [-0.43411852]]
